# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{better_caller}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tim Morgan"]
  s.date = %q{2011-01-04}
  s.description = %q{A more programmer-friendly call stack complete with bindings for each level: no more string parsing!}
  s.email = %q{git@timothymorgan.info}
  s.extensions = ["ext/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.textile"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.textile",
    "Rakefile",
    "VERSION",
    "better_caller.gemspec",
    "ext/better_caller.c",
    "ext/debug.h",
    "ext/dln.h",
    "ext/encdb.h",
    "ext/eval_intern.h",
    "ext/extconf.rb",
    "ext/gc.h",
    "ext/id.h",
    "ext/iseq.h",
    "ext/method.h",
    "ext/node.h",
    "ext/parse.h",
    "ext/regenc.h",
    "ext/regint.h",
    "ext/regparse.h",
    "ext/revision.h",
    "ext/thread_pthread.h",
    "ext/thread_win32.h",
    "ext/timev.h",
    "ext/transcode_data.h",
    "ext/transdb.h",
    "ext/version.h",
    "ext/vm_core.h",
    "ext/vm_exec.h",
    "ext/vm_insnhelper.h",
    "ext/vm_opts.h",
    "lib/better_caller/extensions.rb"
  ]
  s.homepage = %q{http://github.com/RISCfuture/better_caller}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Symbolic call stack with bindings}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_development_dependency(%q<RedCloth>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<RedCloth>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<RedCloth>, [">= 0"])
  end
end

